### ISSUE TITLE
Add questionText

### ISSUE THREAD

**Issue by mariano-aguero** [gnosis/hg-subgraph#24]
I wonder if is possible to add the question Text from realitio to the condition entity, as a field (maybe _questionText_ ?)
Would be great to search by this field

**Comment by mariano-aguero** [comment]
@cag Can we move the questionText to the condition entity ? so we can search with a _contains_ suffix 

Thanks

**Comment by cag** [comment]
Reopening as this field needs to be copied to all Condition entities which rely on a Question entity.
