### ISSUE TITLE
Add total value locked 

### ISSUE THREAD

**Issue by mariano-aguero** [gnosis/hg-subgraph#25]
I wonder if is possible to add a property to the condition entity, `total value locked`. We need to take into account the user will need to sort about this property. Other things to consider, if the value is expresed  using decimals, we need to consider that tokens have different decimals (the values ​​would not be normalized), I don't know how we can solve this.

Initial request from here https://github.com/gnosis/conditional-tokens-explorer/issues/340

**Comment by cag** [comment]
Closing this for now due to https://github.com/gnosis/conditional-tokens-explorer/issues/340#issuecomment-708689775
