### ISSUE TITLE
Space in the middle of conditionIdsStr

### ISSUE THREAD

**Issue by mariano-aguero** [gnosis/hg-subgraph#28]
I tried to use this query 

```
{
  positions(first: 1000, where:{conditionIdsStr_contains: " "}) {
    id
    conditionIdsStr
  }
}
```
In the playground https://thegraph.com/explorer/subgraph/cag/hg-rinkeby?selected=playground

And I detect that some conditionIds have an space in the middle, and others don't

I also checked this in the panel, and corroborated this problem, I wonder if there is something that I need to know ?
Is possible to remove this space and join all the conditions without a separator ?

![Peek 30-10-2020 18-32](https://user-images.githubusercontent.com/1144028/97758952-bd8b0a80-1ade-11eb-8e15-ecbdb9942cb0.gif)

Thanks in advance

**Comment by cag** [comment]
Yeah, I formatted the conditionIdsStr that way by `.join(" ")`, so positions with more than one condition have a space, but can just join with an empty string instead.

**Comment by mariano-aguero** [comment]
> Yeah, I formatted the conditionIdsStr that way by `.join(" ")`, so positions with more than one condition have a space, but can just join with an empty string instead.

Great! This will solve an usability problem, thanks
