### ISSUE TITLE
Add counter to fetch more than 1000 elements

### ISSUE THREAD

**Issue by mariano-aguero** [gnosis/hg-subgraph#29]
TheGraph returns at most 1000 elements, the best way would be to have a positions counter in the subgraph and to use that counter to create multiples queries to get the complete set of positions

And example of this can be found here https://github.com/protofire/maker-governance-subgraph/blob/master/src/helpers.ts#L62

Also, can this be made for the position and condition entities ?

Thanks

**Comment by cag** [comment]
This is about counting positions and conditions and putting that info somewhere like in a global singleton.
